

## 异常编写细节

这一章我们将对异常的内涵与外延进行更为深入的挖掘，针对Python中的异常处理语法给出更多的介绍。



### try/except/else语句

从语法上讲，try是一种包含多个块的复合语句。它以try作为首行，后面紧跟着缩进的语句代码，然后是一个或者多个except分句来识别要捕捉的异常以及相应的处理代码块，最后是一个可选的else分句以及相应代码块（else出现时，上面至少要有一个except语句）。

```python
try:
    action()
except NameError:
    ...
except IndexError:
    ...
except TypeError as T:
    ...
```

### 捕获所有异常：空的except分句和Exception异常

使用空的except可以捕获一切异常：

```python
try:
    action()
except:
    ...
```

尽管用起来方便，但是它们也可能捕获到和程序代码无关、意料之外的系统异常，而且可能无意中拦截了属于其他处理程序的异常。

Python3.X之后更强势地支持了一个替代方案来解决这些问题之一：通过捕获一个名为Exception的异常具有一个和空的except几乎相同的效果，但它却会忽略与系统退出相关的异常：

```python
try:
    action()
except Exception:
    ...
```

```python
try:
    x = 1/0
except Exception as X:
    print(X)
  
division by zero
```

也可以将捕捉的异常保存为异常对象，但是在异常处理之后该对象就会自动清除，因此想保存异常需要将其赋值给一个新的变量进行保存。

### try/else分句

如果try中的语句没有异常，则会执行else中的程序代码。注意，只有存在至少一句except的时候，才能使用else语句

```python
try:
    'spam'[3]
except IndexError:
    print('except run')
else:
    print('else run')
finally:
    print('finally run')
>>> print('after run')
else run
finally run
after run
```

### try/finally语句

finally语句用在try、except语句之后，即无论异常是否发生，都会执行这一句。因此可以在这一部分定义必须要完成的动作，如文件的关闭或者服务器断开连接等等。

```python
try:
    X = 1/0
except IndexError:
    print('except run')
else:
    print('else run')
finally:
    print('finally run')
    print('after run')
    
finally run
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-4-a84d5a28ebb5> in <module>
      2 
      3 try:
----> 4     X = 1/0
      5 except IndexError:
      6     print('except run')

ZeroDivisionError: division by zero
```

这个例子可以看出，即使报错，也会执行finally中的语句，输出打印信息。

### raise语句

如果要显示地触发异常，你可以使用raise语句

```python
try:
    raise IndexError('spam')
except IndexError:
    print('propagating')
    raise

propagating
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-8-30f65ef43030> in <module>
      1 try:
----> 2     raise IndexError('spam')
      3 except IndexError:
      4     print('propagating')
      5     raise

IndexError: spam
```

使用raise语句可以直接将异常传递至上一层，使用raise嵌套，则会使语句回到上一次异常出现的地方。

### 异常链：raise from

当from分句被使用在一个显式raise请求的时候，from后面跟的表达式指定了另一个异常类或实例，该异常会附加到新引发异常的\_\_cause\_\_属性。如果新引发的异常没有被捕获，那么Python会把两个异常都作为标准出错信息的一部分打印出来

```python
try:
    try:
        raise IndexError()
    except Exception as E:
        raise TypeError() from E
    finally:
        print("finally run")

except Exception as R:
    raise SyntaxError() from R
finally:
    print("finally run")
   

finally run
finally run
Traceback (most recent call last):

  File "<ipython-input-1-bb64251948eb>", line 3, in <module>
    raise IndexError()

IndexError


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "<ipython-input-1-bb64251948eb>", line 5, in <module>
    raise TypeError() from E

TypeError


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/home/disk1/lxw2020/anaconda3/envs/py3/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-bb64251948eb>", line 10, in <module>
    raise SyntaxError() from R

  File "<string>", line unknown
SyntaxError
```

### raise from None

这条语句能禁用之前提到的连锁异常上下文的显示，只会显示最近的一条异常信息。

### assert语句

assert语句格式为：assert test,data

如果test语句为假，就会触发异常（AssertionError）：data项将作为异常构造函数的参数。

常用来捕获约束条件

```python
def f(x):
    assert x<0, 'x must be negative'
    return x**2

>>> f(1)

AssertionError                            Traceback (most recent call last)
<ipython-input-13-281ab0a37d7d> in <module>
----> 1 f(1)

<ipython-input-12-9ad5be1a5673> in f(x)
      1 def f(x):
----> 2     assert x<0, 'x must be negative'
      3     return x**2
      4 

AssertionError: x must be negative
```

